// Custom service worker — merged with Workbox-generated SW by vite-plugin-pwa
// This file handles push events and notification clicks.

import { precacheAndRoute } from 'workbox-precaching'

// Workbox injects the asset manifest here at build time
precacheAndRoute(self.__WB_MANIFEST)

// ── Push event handler ────────────────────────────────────────────────────────
self.addEventListener('push', (event) => {
  if (!event.data) return

  let payload
  try {
    payload = event.data.json()
  } catch {
    payload = { title: 'The Rustic Vine', body: event.data.text() }
  }

  const { title = 'The Rustic Vine', body = '', url = '/', type = 'general' } = payload

  const iconMap = {
    live:    '/icons/icon-192.png',
    product: '/icons/icon-192.png',
    blog:    '/icons/icon-192.png',
    general: '/icons/icon-192.png',
  }

  const options = {
    body,
    icon:  iconMap[type] || '/icons/icon-192.png',
    badge: '/icons/icon-192.png',
    data:  { url },
    tag:   type, // collapse same-type notifications
    renotify: true,
    vibrate:  [100, 50, 100],
    actions: [
      { action: 'open',    title: type === 'live' ? '▶ Watch Live' : '→ View' },
      { action: 'dismiss', title: 'Dismiss' },
    ],
  }

  event.waitUntil(
    self.registration.showNotification(title, options)
  )
})

// ── Notification click handler ────────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  if (event.action === 'dismiss') return

  const targetUrl = event.notification.data?.url || '/'

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Focus existing window if already open
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(targetUrl)
          return client.focus()
        }
      }
      // Open a new window
      if (clients.openWindow) {
        return clients.openWindow(targetUrl)
      }
    })
  )
})

// ── Offline fallback (injected by Workbox) ────────────────────────────────────
// Workbox precaching and runtime caching is auto-generated by vite-plugin-pwa
// and merged with this file at build time.
